package Vistas;

import Control.ResiduosControl;
import Control.TrasladosControl;
import ObjetosNegocio.Residuo;
import ObjetosNegocio.Transportadora;
import ObjetosNegocio.Traslado;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.Date;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

public class RegistroTraslado extends javax.swing.JFrame implements ActionListener {

    private Transportadora transportadora;
    private ResiduosControl residuoControl;
    private TrasladosControl trasladorControl;

    public RegistroTraslado(Transportadora transportadora) {
        initComponents();
        this.transportadora = transportadora;
        this.residuoControl = new ResiduosControl();
        this.trasladorControl = new TrasladosControl();

        jButtonRegistrar.addActionListener(this);
        jButtonRegistrar.setActionCommand("Registrar");
        this.jLabelNombreEmpresa.setText("Empresa Transportadora: " + transportadora.getNombre());
        jComboBoxResiduos.setModel(new DefaultComboBoxModel());
        fillComboBox();

        setVisible(true);
    }

    @Override
    public void actionPerformed(ActionEvent ae) {
        String action = ae.getActionCommand();

        switch (action) {

            case "Registrar":
                registrar();
                break;
        }
    }

    private void fillComboBox() {
        DefaultComboBoxModel model = new DefaultComboBoxModel();

        for (Residuo r : residuoControl.findAll()) {
            model.addElement(r.getNombre() + "  (" + r.getCodigo() + ")");
        }

        jComboBoxResiduos.setModel(model);
    }

    private void registrar() {
        String origen = jTextFieldOrigen.getText();
        String destino = jTextFieldDestino.getText();
        String tratamiento = jTextFieldTratamiento.getText();
        String medioTransporte = jTextFieldMedioTransporte.getText();

        Date salida = null;
        Date llegada = null;
        boolean salidaMatch = Regex.Regex.matchDate(jTextFieldFechaYear.getText(), jTextFieldFechaMonth.getText(), jTextFieldFechaDay.getText());
        boolean llegadaMatch = Regex.Regex.matchDate(jTextFieldFechaLlegadaYear.getText(), jTextFieldFechaLlegadaMonth.getText(), jTextFieldFechaLlegadaDay.getText());

        if (salidaMatch && llegadaMatch) {
            int salidaDay = Integer.parseInt(jTextFieldFechaDay.getText());
            int salidaMonth = Integer.parseInt(jTextFieldFechaMonth.getText());
            int salidaYear = Integer.parseInt(jTextFieldFechaYear.getText());
            salida = new Date(salidaYear - 1900, salidaMonth - 1, salidaDay);

            int llegadaDay = Integer.parseInt(jTextFieldFechaLlegadaDay.getText());
            int llegadaMonth = Integer.parseInt(jTextFieldFechaLlegadaMonth.getText());
            int llegadaYear = Integer.parseInt(jTextFieldFechaLlegadaYear.getText());
            llegada = new Date(llegadaYear - 1900, llegadaMonth - 1, llegadaDay);
        } else {
            JOptionPane.showMessageDialog(rootPane, "Ingrese fecha valida por favor!");
        }

        Residuo residuo = getResiduoSeleccionado();
        Traslado t = new Traslado(residuo, origen, destino, salida, llegada, tratamiento, transportadora, medioTransporte);
        boolean b = trasladorControl.insertOne(t);
        if (b) {
            this.setVisible(false);
            JOptionPane.showMessageDialog(rootPane, "Traslado Registrado Exitosamente!");

        } else {
            JOptionPane.showMessageDialog(rootPane, "Traslado no se Registró Exitosamente!");
        }
    }

    private Residuo getResiduoSeleccionado() {
        DefaultComboBoxModel model = new DefaultComboBoxModel();
        String s = (String) jComboBoxResiduos.getSelectedItem();
        s = s.split("[\\(\\)]")[1];
        int codigo = Integer.parseInt(s);

        return residuoControl.findByCode(codigo);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabelNombreEmpresa = new javax.swing.JLabel();
        jLabelOrigen = new javax.swing.JLabel();
        jTextFieldOrigen = new javax.swing.JTextField();
        jLabelDestino = new javax.swing.JLabel();
        jTextFieldDestino = new javax.swing.JTextField();
        jLabelFecha = new javax.swing.JLabel();
        jTextFieldFechaDay = new javax.swing.JTextField();
        jTextFieldFechaMonth = new javax.swing.JTextField();
        jTextFieldFechaYear = new javax.swing.JTextField();
        jLabelFechaLlegada = new javax.swing.JLabel();
        jTextFieldFechaLlegadaDay = new javax.swing.JTextField();
        jTextFieldFechaLlegadaMonth = new javax.swing.JTextField();
        jTextFieldFechaLlegadaYear = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jTextFieldTratamiento = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jTextFieldMedioTransporte = new javax.swing.JTextField();
        jComboBoxResiduos = new javax.swing.JComboBox<>();
        jLabel12 = new javax.swing.JLabel();
        jButtonRegistrar = new javax.swing.JButton();

        jLabel3.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel3.setText("Registro de Traslado");

        jLabelNombreEmpresa.setText("Empresa Trasportadora: Nombre Empresa");

        jLabelOrigen.setText("Origen: ");

        jLabelDestino.setText("Destino: ");

        jLabelFecha.setText("Fecha Salida: ");

        jTextFieldFechaDay.setText("DD");

        jTextFieldFechaMonth.setText("MM");

        jTextFieldFechaYear.setText("YYYY");

        jLabelFechaLlegada.setText("Fecha Llegada: ");

        jTextFieldFechaLlegadaDay.setText("DD");

        jTextFieldFechaLlegadaMonth.setText("MM");

        jTextFieldFechaLlegadaYear.setText("YYYY");

        jLabel10.setText("Tratamiento Posterior: ");

        jLabel11.setText("Medio de Transporte: ");

        jComboBoxResiduos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel12.setText("Seleccione Residuo:");

        jButtonRegistrar.setText("Registrar");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(106, 106, 106)
                        .addComponent(jLabel3))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabelOrigen)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldOrigen, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabelDestino)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldDestino))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabelFechaLlegada)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTextFieldFechaLlegadaDay, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                            .addComponent(jLabelFecha)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(jTextFieldFechaDay, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jTextFieldFechaMonth, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                                            .addComponent(jTextFieldFechaLlegadaMonth))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jTextFieldFechaYear, javax.swing.GroupLayout.DEFAULT_SIZE, 53, Short.MAX_VALUE)
                                            .addComponent(jTextFieldFechaLlegadaYear)))
                                    .addComponent(jTextFieldTratamiento)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldMedioTransporte))
                            .addComponent(jComboBoxResiduos, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabelNombreEmpresa)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(144, 144, 144)
                        .addComponent(jLabel12))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(162, 162, 162)
                        .addComponent(jButtonRegistrar)))
                .addContainerGap(113, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addGap(12, 12, 12)
                .addComponent(jLabelNombreEmpresa)
                .addGap(40, 40, 40)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelOrigen)
                    .addComponent(jTextFieldOrigen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelDestino)
                    .addComponent(jTextFieldDestino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelFecha)
                    .addComponent(jTextFieldFechaDay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldFechaMonth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldFechaYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelFechaLlegada)
                    .addComponent(jTextFieldFechaLlegadaDay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldFechaLlegadaMonth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldFechaLlegadaYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jTextFieldTratamiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jTextFieldMedioTransporte, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBoxResiduos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonRegistrar)
                .addContainerGap(27, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

//    /**
//     * @param args the command line arguments
//     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(RegistroTraslado1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(RegistroTraslado1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(RegistroTraslado1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(RegistroTraslado1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new RegistroTraslado1().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonRegistrar;
    private javax.swing.JComboBox<String> jComboBoxResiduos;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabelDestino;
    private javax.swing.JLabel jLabelFecha;
    private javax.swing.JLabel jLabelFechaLlegada;
    private javax.swing.JLabel jLabelNombreEmpresa;
    private javax.swing.JLabel jLabelOrigen;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField jTextFieldDestino;
    private javax.swing.JTextField jTextFieldFechaDay;
    private javax.swing.JTextField jTextFieldFechaLlegadaDay;
    private javax.swing.JTextField jTextFieldFechaLlegadaMonth;
    private javax.swing.JTextField jTextFieldFechaLlegadaYear;
    private javax.swing.JTextField jTextFieldFechaMonth;
    private javax.swing.JTextField jTextFieldFechaYear;
    private javax.swing.JTextField jTextFieldMedioTransporte;
    private javax.swing.JTextField jTextFieldOrigen;
    private javax.swing.JTextField jTextFieldTratamiento;
    // End of variables declaration//GEN-END:variables
}
